### ISSUE TITLE
Error while downloading the video

### ISSUE THREAD

**Issue by dolphin221** [YouTubeDownload/YouTubeDownload#10]
> **Traceback (most recent call last):
 File "...\YouTubeDownload\qt_assets\tabs\downloader.py", line 95, in load_streams
self.sig_error.emit(e)
TypeError: StreamLoader.sig_error[str].emit(): argument 1 has unexpected type 'KeyError'
QObject::~QObject: Timers cannot be stopped from another thread**

**Comment by jslay88** [comment]
https://github.com/YouTubeDownload/YouTubeDownload/releases/tag/v2.1
