### ISSUE TITLE
pytube3

### ISSUE THREAD

**Issue by hbmartin** [YouTubeDownload/YouTubeDownload#12]
Hello, opening this issue to let you know that there is a new, actively maintained, Python3 only pytube fork: https://github.com/hbmartin/pytube3

I'm also looking for an official GUI frontend, if you're interested.

**Comment by jslay-excella** [comment]
Fork the repo and open a PR. More than willing to add others to the project.

**Comment by jslay88** [comment]
Fork the repo and open a PR. More than willing to add others to the project.

**Comment by hbmartin** [comment]
https://github.com/YouTubeDownload/YouTubeDownload/pull/13
