### ISSUE TITLE
Executed on deepin linux Error: GLIBC_2.29

### ISSUE THREAD

**Issue by djwesleyborges** [YouTubeDownload/YouTubeDownload#18]
[32427] Error loading Python lib '/tmp/_MEIDdlMZ1/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIDdlMZ1/libpython3.7m.so.1.0)

**Comment by jslay88** [comment]
deepin uses an old glibc version, for which we probably aren't going to build specific one-file binaries for. They also don't have Python 3.6+ which is required for the new version of pytube being used.  So this would be hard for us to support. Someone with more experience making linux one-files might be able to chime in and assist with automating it somehow, but AFAIK, everything on a linux OS just about depends on glibc, so you would have to install a specific OS just to build for that version reliably. 

You would have to build Python 3.6+ on the system first, create venv, install requirements, install pyinstaller, and run the pyinstaller command to build it for yourself.
