### ISSUE TITLE
Non-BPM character

### ISSUE THREAD

**Issue by nthomasCUBE** [YouTubeDownload/YouTubeDownload#20]
hi,
great tool, maybe you find a workaround for cases where the video.title
contains strange characters, e.g. try-catch or so
as video can be still downloaded

br

download_youtube_video.py", line 43, in download_youtube_video
print('Download Started: %s' % video.title)
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 79-79: Non-BMP character not supported in Tk

**Comment by jslay88** [comment]
Can you provide a url to a video that does this?

**Comment by nthomasCUBE** [comment]
Hi,
could not find the actual video, but have the same problem with all videos
where the titel contains an icon 
e.g. https://www.youtube.com/watch?v=oCVwxDZ-Pt8
br

**Comment by jslay88** [comment]
Works for me.

Need OS, OS build, Python Version, output of pip list.

**Comment by nthomasCUBE** [comment]
right, i used script.py directly not the gui...would have to install some packages
Python 3.7.0 (v3.7.0:1bf9cc5093) [MSC v.1914 64 bit (AMD64)] on win32

br

**Comment by jslay88** [comment]
Works for me still on Windows 10, Python 3.7 64bit

```
(venv) C:\Scripts\YouTubeDownload>python script.py
...

To Download Video/Audio Y/n: y
Enter Url: https://www.youtube.com/watch?v=oCVwxDZ-Pt8
Do you want to download video or audio: video
Download Started: How To Make Thumbnails For YouTube Videos On Android �
Download Complete! Saved to file: How To Make Thumbnails For YouTube Videos On Android �.mp4
```

**Comment by nthomasCUBE** [comment]
you are right,
agrees with https://stackoverflow.com/questions/32442608/ucs-2-codec-cant-encode-characters-in-position-1050-1050

i used the Python IDLE 3.7 on  windows that is build upon Tk which can not display these symbols

quess then it is not really a problem, i will close the issue,
many thanks for all the efforts!

**Comment by jslay88** [comment]
Run it through cmd and all should be good.
