### ISSUE TITLE
Stream issue

### ISSUE THREAD

**Issue by rt23456p** [YouTubeDownload/YouTubeDownload#22]
![sc-1](https://user-images.githubusercontent.com/31880587/84119330-cb27f100-aa66-11ea-8d7f-108d69dffaa4.PNG)
![image](https://user-images.githubusercontent.com/31880587/84119339-cc591e00-aa66-11ea-9831-1119721ed619.png)

The software works great for normal videos, but for live stream, it doesn't work, even if it's after the full stream.

**Comment by jslay88** [comment]
I don't think pytube will ever support the ability to download an active live stream. I do have some changes that would potentially make the post-stream downloadable, but there are also some caveats that come with those, such as, I am unable to detect the video name for live streams (even the post-stream video), and it just defaults to "YouTube" for the video name. 

I recommend opening an issue with pytube3 to see if there is something they can address on their end, as this is where the problem really needs to be solved.

https://github.com/get-pytube/pytube3

**Comment by rt23456p** [comment]
> I don't think pytube will ever support the ability to download an active live stream. I do have some changes that would potentially make the post-stream downloadable, but there are also some caveats that come with those, such as, I am unable to detect the video name for live streams (even the post-stream video), and it just defaults to "YouTube" for the video name.
> 
> I recommend opening an issue with pytube3 to see if there is something they can address on their end, as this is where the problem really needs to be solved.
> 
> https://github.com/get-pytube/pytube3

Thx for the reply, I am trying to download a post-stream anyways, but it don't work for some reasons

**Comment by jslay88** [comment]
Yes, as my comment stated, I am aware. The issue still exists with pytube.
