### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by arsider** [YouTubeDownload/YouTubeDownload#23]
Hi,
Thanks for this little but very useful utility. I already used some months ago and it worked fine. But lately, I tried to download a youtube video and have been sparked with "This video is unvailable".
Could you help see what changed maybe in the Youtube API ?
Thanks.

**Comment by jslay88** [comment]
You have provided very little details and have made a poor bug report and given me very little to go off of. The tool still works.

**Comment by arsider** [comment]
Hi @jslay88,
Sorry , false alarm. I am using Homebrew under mac os x 10.13.6 which ships its own 3.7 python which I never use. Usually I am using my Anaconda Python 3.x which have the good uptodate requirements (pytube, pyQt5, and requests ). 
Simply reverting/using my usual python distribution with up-to-date requirements solved the issue.
Sorry for the false issue reporting that I am closing hereby.
Thanks for the good work and for your fast reaction.
