### ISSUE TITLE
No 3.8 Support

### ISSUE THREAD

**Issue by bryaend** [YouTubeDownload/YouTubeDownload#29]
When running, I get the following error:

```
PS C:\Users\bendr\Documents\Python Scripts\YouTubeDownload> py .\script.py
Requested Python version (3.6) is not installed
PS C:\Users\bendr\Documents\Python Scripts\YouTubeDownload>
```

I am running 3.8, should this really be an issue?

`Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32`

**Comment by jslay88** [comment]
`script.py` has a `3.6` erroneously on the first line shebang. change it to `3`. Will update.
