### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MilkMan1093** [YouTubeDownload/YouTubeDownload#31]
Error HTTP Error 410: Gone while downloading [this video](https://www.youtube.com/watch?v=wFhdShArqJo)

**Comment by BouncyBird** [comment]
Yes, this a PyTube problem that recently arose. I ran into this problem, when using the PyTube library recently. I was able to fix it by installing a patch I found in this [StackOverflow answer](https://stackoverflow.com/a/68682344/16117401). I think the developer of YouTubeDownload will need to include this patch in the YouTubeDownload software.

**Comment by jslay88** [comment]
From old `pytube` version, new `pytube` version has different issue now. Waiting for update. Tracking on #28
