### ISSUE TITLE
script + command-line arguments; any soln for youtube IDs with "--[InsertIDHere]"?

### ISSUE THREAD

**Issue by layagollapudi** [YouTubeDownload/YouTubeDownload#9]

**Comment by jslay88** [comment]
Not quite sure I understand the question. 

You can clone the repo and use script.py to download. You could also use script.py as an example for how to use the modules themself. 

Here is a direct way to download in one line. ITAG numbers are the same dependening on the streams properties, from video to video. Ergo, every 720p video has a 278 ITAG.

python3 script.py -u rfscVS0vtbw -i 278 -o videos/ -f my_downloaded_itag_video
